language: node_js

node_js:
  - "0.12"

sudo: false

env:
  - MODULE=context
  - MODULE=default

before_install:
  - openssl aes-256-cbc -K $encrypted_ba78ad1c8b3e_key -iv $encrypted_ba78ad1c8b3e_iv
      -in service-account.json.enc -out service-account.json -d

install:
# Install for Go App Engine build
  - export FILE=$(curl https://storage.googleapis.com/appengine-sdks/ | grep -o 'featured/go_appengine_sdk_linux_amd64-[^\<]*' | tail -n 1 | grep -o 'go_appengine_.*')
  - echo $FILE
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE
# Install for Nodejs/Grunt build
  - cd ${TRAVIS_BUILD_DIR}/$MODULE
  - npm install

script:
  - cd ${TRAVIS_BUILD_DIR}/$MODULE
# Go App Engine build
  - ${TRAVIS_BUILD_DIR}/go_appengine/goapp get -d ./src
  - ${TRAVIS_BUILD_DIR}/go_appengine/goapp build ./src
# Nodejs/grunt build
  - node_modules/.bin/bower install
  - node_modules/.bin/grunt

deploy:
  provider: gae
  keyfile: "${TRAVIS_BUILD_DIR}/service-account.json"
  default: false
  project: gamescores-info
  version: $TRAVIS_BRANCH
  config: ${TRAVIS_BUILD_DIR}/$MODULE/$MODULE.yaml

cache:
  directories:
    - $MODULE/node_modules
    - $MODULE/bower_components