language: node_js

node_js:
  - "0.12"

sudo: false

env:
  - MODULE=context
  - MODULE=default

install:
# Install for Go App Engine build
  - export FILE=$(curl https://storage.googleapis.com/appengine-sdks/ | grep -o 'featured/go_appengine_sdk_linux_amd64-[^\<]*' | tail -n 1 | grep -o 'go_appengine_.*')
  - echo $FILE
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE
# Install for Nodejs/Grunt build
  - cd ${TRAVIS_BUILD_DIR}/$MODULE
  - npm install

script:
  - cd ${TRAVIS_BUILD_DIR}/$MODULE
# Go App Engine build
  - ${TRAVIS_BUILD_DIR}/go_appengine/goapp get -d ./src
# goapp build doesn't build the same way as goapp serve and goapp deploy. So for now just deploy the code. That will
# compile as well. If anyone wants to improve then maybe look into go-app-builder, which is being used when goapp serve
# is being used.
#  - ${TRAVIS_BUILD_DIR}/go_appengine/goapp build ./src
# Nodejs/grunt build
  - node_modules/.bin/bower install
  - node_modules/.bin/grunt

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ${TRAVIS_BUILD_DIR}/go_appengine/appcfg.py --oauth2_refresh_token=$OAUTH2_REFRESH_TOKEN --oauth2_client_id=$OAUTH2_CLIENT_ID --oauth2_client_secret=$OAUTH2_CLIENT_SECRET update -V $TRAVIS_BRANCH -A gamescores-info ${TRAVIS_BUILD_DIR}/$MODULE/$MODULE.yaml || false'
