application: gamescores-info
module: default
api_version: go1
runtime: go

handlers:
- url: /api/.*
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index\.html

env_variables:
  GIN_MODE: "release"
